apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-deploy-file
  labels:
    app: backend.v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend.v1
  template:
    metadata:
      labels:
        app: backend.v1
    spec:
      containers:
      - name: latest
        image: backend.v1:latest
        ports:
         - containerPort:8080
     
