FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore && dotnet publish -c Release -o ./out

#Runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/src/Conduit/out/ .
ENTRYPOINT ["dotnet", "Conduit.dll"]
EXPOSE 5000