apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy-file
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      - name: latest
        image: frontend:latest
        ports:
         - containerPort:4100
     
